definitions:
  model.Article:
    properties:
      author:
        type: string
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      is_deleted:
        type: boolean
      likes:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    required:
    - author
    - content
    - id
    - title
    type: object
  model.Author:
    properties:
      created_at:
        type: string
      full_name:
        type: string
      id:
        type: string
      updated_at:
        type: string
    required:
    - full_name
    - id
    type: object
info:
  contact: {}
paths:
  /v1/article/{id}:
    get:
      consumes:
      - application/json
      description: Get article by given ID.
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
      summary: get article by given ID
      tags:
      - Article
  /v1/author:
    post:
      consumes:
      - application/json
      description: Create author by given Body.
      parameters:
      - description: Author
        in: body
        name: author
        required: true
        schema:
          $ref: '#/definitions/model.Author'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Author'
      summary: get author by given ID
      tags:
      - Author
  /v1/author/{id}:
    get:
      consumes:
      - application/json
      description: Get author by given ID.
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Author'
      summary: get author by given ID
      tags:
      - Author
swagger: "2.0"
